<a href="https://colab.research.google.com/github/VeraaaaWei/data_analytics/blob/Python/1.13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
import numpy as np

np_city = np.array([['NYC','LA'],['k','j']])
np_city.shape






(2, 2)

In [21]:
import numpy as np

np_city_with_state = np.array(['NYC','LA','Houston'])
np_city_with_state.shape


(3,)

In [5]:
first = [9,8,7]
second = [6,5,4]

np_f = np.array(first)
np_s = np.array(second)

np_f + np_s

array([15, 13, 11])

In [15]:
first = [9,8,7]
second = [6,5,4]
cyc = np.array([[9,8,7],[6,5,4]])
ft = cyc[0]
fts = cyc[0,0]
st = cyc[1]
sts = cyc[1,0]
print(ft)
print(fts)
print(st)
print(sts)


[9 8 7]
9
[6 5 4]
6


In [17]:
first = [9,8,7]
second = [6,5,4]
cyc = np.array([first, second])
ft = cyc[0]
fts = cyc[0,0]
st = cyc[1]
sts = cyc[1,0]
print(ft)
print(fts)
print(st)
print(sts)


[9 8 7]
9
[6 5 4]
6


In [18]:
ts = np.array([[1,2,3],[4,5,6]])
ps = ts>2
ts[ps]



array([3, 4, 5, 6])

In [22]:
NYCB = np.array(['M','Q','B','S','BR'])
NYCB

array(['M', 'Q', 'B', 'S', 'BR'], dtype='<U2')

In [29]:
NYCB = np.array(['M','Q','B','S'])
NYCB

BNYC = NYCB
BNYC
BSNYC = BNYC.view()
BSNYC

NYCB is BNYC

len(BSNYC)

BSNYC[3]

'S'

In [39]:


from numpy import pi
np.cos(0)
np.sin(pi/2)
np.cos(pi)
np.floor([2.3,3,4.5,-1.9])
np.exp([0,1,3])

array([ 1.        ,  2.71828183, 20.08553692])

In [37]:
np_sqrt =np.sqrt([2,3,4,5])
np_sqrt

array([1.41421356, 1.73205081, 2.        , 2.23606798])

In [41]:
a = np.array([9,8,7])
b = np.array([6,5,4])
a*b
c = 0.3
a*c

array([2.7, 2.4, 2.1])

In [46]:
inve = np.array([[1,2],[9,8]])
np.linalg.inv(inve)

array([[-0.8,  0.2],
       [ 0.9, -0.1]])